name: Simple CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install API dependencies
        run: |
          cd apps/api
          npm install

      - name: Install frontend dependencies
        run: |
          cd apps/desktop
          npm install

      - name: Start API server
        run: |
          cd apps/api
          npm run dev &
          sleep 20

      - name: Start frontend server
        run: |
          cd apps/desktop
          npm run dev &
          sleep 15

      - name: Install Playwright browsers
        working-directory: apps/desktop
        run: npx playwright install

      - name: Run Playwright tests
        working-directory: apps/desktop
        run: npx playwright test

      - name: Stop servers
        run: kill $(jobs -p) || true